# Chap.2 &mdash; _numpy.ndarray_.

_Jean-Christophe Taveau, Université de Bordeaux, 2023-2024_

> **Pre-requisites**: Basics of Python - variables, loops, conditionals, functions

## 1. Introduction

The documentation is available in the Numy official website [numpy.ndarray](https://numpy.org/doc/stable/reference/arrays.ndarray.html).

Why are we using `numpy.ndarray`? mostly, for speed and here is an element of comparison...

### 1.1. _Numpy_ speeeeeddd !!!!

The script below builds a 2D array containing incremented floating numbers using traditional Python with two nested loops.

In [3]:
%%timeit
# Uncomment the line above to estimate your CPU computation time for this script

L=[]
v = 0
for y in range(400):
    row = []
    for x in range(680):
        row.append(v)
        v += 1
    L.append(row)


18.3 ms ± 1.6 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)


... and here is the _numpy_ version.

In [4]:
%%timeit
# Uncomment the line above to estimate your CPU computation time for this script

import numpy as np

np.arange(400*680).reshape(400,680)

95.5 µs ± 484 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


> **Note**: We'll see later in this chapter, the meaning of all these functions.

On my laptop, I got the following CPU time and `numpy` is a champion in speed!!

|Code | Computation time |
|-----|------------------|
| Python  | 13.5 ms ± 78.7 µs per loop (mean ± std. dev. of 7 runs, 100 loops each) | 
| numpy   | 75.3 µs ± 125 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each) |

### 1.2. Comparison with _pandas.DataFrame_

|              | DataFrame | Numpy Array | Note |
|--------------|-----------|-------------|--------|
| Dimension Number   | 2D        | 1D,2D,3D up to nD | n=no theoritical limit |
| Column Headings | Yes | No | |
| Mixing datatype | Yes | No | see script below |


### 1.3. Data types

In a numpy array, you cannot mix different data types. From a heterogeneous array, `numpy` tries to automatically convert the data into a homogeneous compatible type. As noticed in the following script, the array `a` is defined from a _List_ of a mixture of _Number_ and _String_ which are converted into a _String_ numpy array.

In [5]:
# Creating a numpy array containing mixing data types (Number and String)
a = np.array([0,1.345,2,'BIP'])

# All the elements of `a` are converted as String
a

array(['0', '1.345', '2', 'BIP'], dtype='<U32')

The datatypes available in numpy array correspond to those used by the programming language C/C++. A full description is available [here](https://numpy.org/doc/stable/user/basics.types.html#data-types).

Most of the time, during the creation &mdash; if the datatype is not specified &mdash; `numpy` tries to guess the best type suitable for your data.

In [6]:
a =  np.array([0,12,1234]) # int because there is no floating-point number (aka real number)
b =  np.array([0,1.345,3.14]) # float 
c =  np.array(['Bordeaux','Goettingen','Groningen']) # String
d =  np.array([0,12,224],dtype=np.uint8) # Force the datatype to be an unsigned 8-bit integer.

f'a:{a.dtype}, b:{b.dtype}, c: {c.dtype}, d:{d.dtype}'

'a:int64, b:float64, c: <U10, d:uint8'

However, as shown in the script below, the type of the array may change in function of the operation you applied to your data. 

In [7]:
a1 = a / 2    # int64 -> float64
a2 = a // 2   # int64 -> int64
ab = a + b    # int64 + float64 -> float64

f'a1:{a1.dtype}, a2:{a2.dtype}, ab:{ab.dtype}'

'a1:float64, a2:int64, ab:float64'

> **Warning**: Specifying data type may give weird result.
> 
> The array `d` contains three values [0, 12, 224] and the datatype is forced to `uint8`. If you multiply this array by four (4), you expect to get:
> - 0 * 4 = 0
> - 12 * 4 = 48
> - 224 * 4 = 896 !!! Problem
>
> The last element is greater than the maximum value authorized for a `uint8`(255<sub>(10)</sub> = 2<sup>8</sup> - 1 = 11111111<sub>(2)</sub> ). Thus, the value is recalculated according to this formula corresponding to a permutation `value = (224 * 4) % 256 = 128 = 256 * 4 + 128`.

In [8]:
# uint8: range of 0 up to 255
d =  np.array([0,12,225],dtype=np.uint8)
d1 = d * 4

# Expected result
# array([  0,  48, 896])
d1

array([  0,  48, 132], dtype=uint8)

In such a case, you have to convert your data in a data type compatible to your computation. You can do that with the method `astype(..)`.

In [9]:
d =  np.array([0,12,224],dtype=np.uint8)
# The smallest type fitting the value 896 is an unsigned 16-bit integer whose max value is 2^16 - 1 = 65535
d_16bits = d.astype(np.uint16)
d2 = d_16bits * 4
d2

array([  0,  48, 896], dtype=uint16)

## 2. Array creation

In [10]:
import numpy as np

### 2.1.  From a _List_

In [11]:
a = np.array([10,12,45,32,65])
a

array([10, 12, 45, 32, 65])

In [12]:
a.shape,a.dtype

((5,), dtype('int64'))

In [13]:
b=np.array([[1,2,3],[6,5,4],[7,8,9],[12,11,10]])
b
# Result
# array([[ 1,  2,  3],
#        [ 6,  5,  4],
#        [ 7,  8,  9],
#        [12, 11, 10]])

array([[ 1,  2,  3],
       [ 6,  5,  4],
       [ 7,  8,  9],
       [12, 11, 10]])

In [14]:
b.shape

(4, 3)

### 2.2. Initialize a `numpy array`

#### 2.2.1. by a constant value

| Function | Description |
|   ----------   |-------------|
| np.zeros(..) | zero-fill array |
| np.ones(..)  | one-fill array |
| np.full(..) | Array filled with specified value |

This function creates an empty array with undefined values.

| Function | Description |
|   ----------   |-------------|
| np.empty(..) | Empty un-intialized array |

In [15]:
# Init Array with zeroes
empty = np.empty((4,2))
# Init Array with zeroes
zero = np.zeros((2,3,2))
# Init Array with ones
one = np.ones((5,5))
# Init array with arbitrary value
seven = np.full((3,4),7)
empty,zero,one,seven

(array([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]),
 array([[[0., 0.],
         [0., 0.],
         [0., 0.]],
 
        [[0., 0.],
         [0., 0.],
         [0., 0.]]]),
 array([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]),
 array([[7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7]]))

#### 2.2.2. by range values

| Function | Description |
|   ----------   |-------------|
| np.arange(..) | Equivalent to the Python range |
| np.linspace(..) | Linear interpolation between `start` and `stop` in `num` steps |


a = np.arange(10)
b = np.linspace(2.0, 3.0, num=5)
a,b

### 2.3. Exploring the array

These properties are very useful:

- `shape` lists the size of the array. It returns a _tuple_
- `ndim` returns the dimension number. It is equivalent to `len(shape)`.
- `dtype` returns the data type.
- 

In [16]:
a = np.array([[1,2,3],[6,5,4],[7,8,9],[12,11,10]]) 
a.shape,a.ndim,a.dtype

((4, 3), 2, dtype('int64'))

The function `np.info(..)` lists all the parameters of the array

In [17]:
a = np.array([[1,2,3],[6,5,4],[7,8,9],[12,11,10]]) 
np.info(a)

class:  ndarray
shape:  (4, 3)
strides:  (24, 8)
itemsize:  8
aligned:  True
contiguous:  True
fortran:  False
data pointer: 0x600000a8c300
byteorder:  little
byteswap:  False
type: int64


### 2.4. Reshaping the array

A powerful functionality of`numpy array`is the ability to modify its shape (size and dimension number).

In [18]:
a = np.arange(12) # 1D array becomes ...
b = a.reshape(3,4) # a 2D array
c = a.reshape(3,2,2) # a 3D array
d = a.reshape(3,1,2,1,2) # a 5D array
a.shape, b.shape,c.shape,d.shape

((12,), (3, 4), (3, 2, 2), (3, 1, 2, 1, 2))

The reverse operation is `flatten(..)` transforming the nD-array into a 1D array.

In [19]:
d.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

## 3. Manipulating numpy array

### 3.1. Get values and slicing

To read a value in a numpy array, you use the same syntax as the _List_ using square brackets and an index giving the location of the element in the array. The first element of an array is at index 0. Like in _List_, the indexing may use positive or negative numbers. In the latter, the last element is at index -1.

> **Note**: In a multi-dimensional array, you may simplify the syntax by separating the various indexes by commas rather than using the open/close squared brackets.
> 
> For example to read a value in a 4D array `a`, the syntax `a[w][z][y][x]` is equivalent to `a[w,z,y,x]`

In [20]:
a = np.arange(24)
b=np.array([[1,2,3],[6,5,4],[7,8,9],[12,11,10]])
# Read the 12th item in `a`
va = a[12]
# Read the item located at the 3rd row and 2nd column
vb = b[3][2]
# In numpy, you can simplify the syntax and separate the indexes by a comma
vb_short = b[3,2]

va,vb,vb_short

(12, 10, 10)

It is really interesting to get a subset of values in a numpy array. Like Python _List_, we use the square brackets with the `start` index and the `stop` index (excluded) separated by a colon <kbd>:</kbd>.

In [21]:
a = np.arange(24)
# You are extracting element of index 11,12,13,14. The element at index 15 is not taken into account
a[11:15]

array([11, 12, 13, 14])

Extracting a rectangular area in this 2D array is done by specifying a range in each axis like...

In [22]:
a = np.arange(24).reshape(6,4)
# array([[ 0,  1,  2,  3],
#        [ 4,  5,  6,  7],
#        [ 8,  9, 10, 11],
#        [12, 13, 14, 15],
#        [16, 17, 18, 19],
#        [20, 21, 22, 23]])

subset = a[2:5,1:3]
subset

array([[ 9, 10],
       [13, 14],
       [17, 18]])

In [23]:
# Equivalent Python code with nested loops
s = np.zeros((3,2))
for y in range(5 - 2):
    for x in range(3 - 1):
      s[y,x] = a[y+2,x+1]   
s

array([[ 9., 10.],
       [13., 14.],
       [17., 18.]])

If you just set a colon <kbd>:</kbd> without specifying `start` and `stop` index. All the elements corresponding to this axis are taken into account. For example, to extract the column at index 2. You say that you want all the elements along axis 0 and only at the index 2 along axis 1.

In [24]:
other = a[:,2]
other

array([ 2,  6, 10, 14, 18, 22])

In [25]:
# This is equivalent to this Python code
col=[]
for y in range(6):
    col.append(a[y,2])
col

[2, 6, 10, 14, 18, 22]

### 3.2. Understanding the axes

#### 3.2.1. Definition 

Source: **Excerpt from the NumPy documentation**

An **axis** is another term for an **array dimension**. 

- Axes are numbered left to right; axis 0 is the first element in the shape tuple.
- In a two-dimensional vector, the elements of axis 0 are rows and the elements of axis 1 are columns.
- In higher dimensions, the picture changes. NumPy prints higher-dimensional vectors as replications of **row-by-column** building blocks, as in this three-dimensional vector:

In [26]:
a = np.arange(12).reshape(2,2,3)
a
# array([[[ 0,  1,  2],
#         [ 3,  4,  5]],
#        [[ 6,  7,  8],
#         [ 9, 10, 11]]])

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

`a` is depicted as a two-element array whose elements are 2x3 vectors. From this point of view, rows and columns are the final two axes, respectively, in any shape.

This rule helps you anticipate how a vector will be printed, and conversely how to find the index of any of the printed elements. For instance, in the example, the last two values of 8’s index must be 0 and 2. Since 8 appears in the second of the two 2x3’s, the first index must be 1:

In [27]:
a[1,0,2]
# 8

8

A convenient way to count dimensions in a printed vector is to count the square bracket <kbd>[</kbd> symbols after the open-parenthesis. This is useful in distinguishing, say, a (1,2,3) shape from a (2,3) shape:

In [28]:
a = np.arange(6).reshape(2,3)
a.ndim
# 2

2

In [29]:
a
# array([[0, 1, 2],
#        [3, 4, 5]])

array([[0, 1, 2],
       [3, 4, 5]])

In [30]:
a = np.arange(6).reshape(1,2,3)
a.ndim,a
# 3
#
# array([[[0, 1, 2],
#         [3, 4, 5]]])

(3,
 array([[[0, 1, 2],
         [3, 4, 5]]]))

#### 3.2.2. Specifying axis for computation

From this 2D array, we want to compute the mean from all the elements in the array. 

In [31]:
a = np.arange(6)
a2d = a.reshape(2,3)
a2d.shape

(2, 3)

Now, we compute the mean.

In [32]:
a2d.mean()

2.5

Now, if we want to calculate means for each column, you have to specify the axis. Here, this is the axis 0 corresponding to the Y vertical axis

In [33]:
a2d.mean(axis=0)

array([1.5, 2.5, 3.5])

With a loop, the code looks like...

In [34]:
# For each column
for x in range(3):
    # Extract all the elements at X = `x` (aka column)
    row = a2d[:,x]
    N = len(row)
    print(x,sum(row)/N)

0 1.5
1 2.5
2 3.5


In [35]:
a2d.mean(axis=1)

array([1., 4.])

#### Adding a new axis to an existing array

In [36]:
a = np.arange(4)
# Row Vector 
a2 = a[np.newaxis,:] # Add a new dimension 
# Column vector
a22 = a[:,np.newaxis]
a2,a22

(array([[0, 1, 2, 3]]),
 array([[0],
        [1],
        [2],
        [3]]))

## 3.2. Modifying an array


In [37]:
# Input
a = np.arange(5)
b = np.arange(11,16)

# Appending b to a -> shape: (10,)
ab0 = np.append(a,b)
ab1 = np.concatenate([a,b]) 
ab2 = np.hstack([a,b])

# Vertical stacking -> shape: (2,5)
ab3 = np.vstack([a,b])
ab0,ab1,ab2,ab3

(array([ 0,  1,  2,  3,  4, 11, 12, 13, 14, 15]),
 array([ 0,  1,  2,  3,  4, 11, 12, 13, 14, 15]),
 array([ 0,  1,  2,  3,  4, 11, 12, 13, 14, 15]),
 array([[ 0,  1,  2,  3,  4],
        [11, 12, 13, 14, 15]]))

## 4. Exercises

> **Note**: Excerpt from "Numpy 101 Exercises".

### 1. How to create a 1D array?

Difficulty Level: L1
Ezoic

Q. Create a 1D array of numbers from 0 to 9


In [40]:
# Type your code, here
a = np.arange(10)

<details>
    <summary>Answer Q1</summary>
    <hr>
    <pre>
arr = np.arange(10)
    </pre>
</details>

### 2. How to create a boolean array?

Difficulty Level: L1

Q. Create a 3×3 numpy array of all True’s

In [41]:
# Type your code, here
t = np.full((3, 3), True, dtype=bool)
t

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

<details>
    <summary>Answer Q2</summary>
    <hr>
    <pre>
a=np.full((3, 3), True, dtype=bool)

\# Alternate method:
b=np.ones((3,3), dtype=bool)
    </pre>
</details>

### 3. How to extract items that satisfy a given condition from 1D array?

Difficulty Level: L1

Q. Extract all odd numbers from `arr`.

In [42]:
# Input
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Type your code, here
odd = arr[arr % 2 == 1]
odd

array([1, 3, 5, 7, 9])

<details>
    <summary>Answer Q3</summary>
    <hr>
    <pre>
arr[arr % 2 == 1]
    </pre>
</details>

### 4. How to replace items that satisfy a condition with another value in numpy array?

Difficulty Level: L1

Q. Replace all odd numbers in arr with -1

In [45]:
# Input
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Type your code, here
repl_odd = [x if x % 2 == 0 else -1 for x in arr]

repl_odd

[0, -1, 2, -1, 4, -1, 6, -1, 8, -1]

<details>
    <summary>Answer Q4</summary>
    <hr>
    <pre>
arr[arr % 2 == 1] = -1
    </pre>
</details>

### 5. How to replace items that satisfy a condition without affecting the original array?

Difficulty Level: L2

Q. Replace all odd numbers in `arr` with -1 without changing `arr`.

In [46]:
# Input
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Type your code, here
out = np.where(arr % 2 == 1, -1, arr)
out

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

<details>
    <summary>Answer Q5</summary>
    <hr>
    <pre>
out = np.where(arr % 2 == 1, -1, arr)
    </pre>
</details>

### 6. How to reshape an array?

Difficulty Level: L1

Q. Convert a 1D array of ten elements to a 2D array with 2 rows.

In [47]:
# Type your code, here
arr = np.arange(10)
arr.reshape(2, -1)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

<details>
    <summary>Answer Q6</summary>
    <hr>
    <pre>
arr = np.arange(10)
arr.reshape(2, -1)  # Setting to -1 automatically decides the number of cols
    </pre>
</details>

### 7. How to stack two arrays vertically?

Difficulty Level: L2

Q. Stack arrays `a` and `b` vertically

In [49]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

# Type your code, here
stacked = np.vstack([a, b])
stacked
# Expected result
#> array([[0, 1, 2, 3, 4],
#>        [5, 6, 7, 8, 9],
#>        [1, 1, 1, 1, 1],
#>        [1, 1, 1, 1, 1]])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

<details>
    <summary>Answer Q7</summary>
    <hr>
    <pre>

\# Method 1:
np.concatenate([a, b], axis=0)

\# Method 2:
np.vstack([a, b])

\# Method 3:
np.r_[a, b]
    </pre>
</details>

### 8. How to stack two arrays horizontally?

Difficulty Level: L2

Q. Stack the arrays a and b horizontally.


In [50]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

# Type your code, here
new = np.hstack([a, b])
new

# Expected result
#> array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
#>        [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

<details>
    <summary>Answer Q8</summary>
    <hr>
    <pre>

\# Method 1:
np.concatenate([a, b], axis=1)

\# Method 2:
np.hstack([a, b])

\# Method 3:
np.c_[a, b]
    </pre>
</details>

### 9. How to get the common items between two python numpy arrays?

Difficulty Level: L2

Q. Get the common items between `a` and `b`

In [51]:
# Input
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

# Type your code, here
common_items = np.intersect1d(a, b)
common_items
# Expected result
#> array([2, 4])

array([2, 4])

<details>
    <summary>Answer Q9</summary>
    <hr>
    <pre>
np.intersect1d(a,b)
    </pre>
</details>

### 10. How to get the positions where elements of two arrays match?

Difficulty Level: L2

Q. Get the positions where elements of `a` and `b` match.

In [52]:
# Input:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

# Type your code, here
match = np.where(a == b)
match
# Expected Output:
#> (array([1, 3, 5, 7]),)

(array([1, 3, 5, 7]),)

<details>
    <summary>Answer Q10</summary>
    <hr>
    <pre>
np.where(a == b)
    </pre>
</details>

### 11. How to extract all numbers between a given range from a numpy array?

Difficulty Level: L2

Q. Get all items from `a` whose values are between 5 and 10.

In [53]:
# Input
a = np.array([2, 6, 1, 9, 10, 3, 27])

# Type your code, here
range = a[(a >= 5) & (a <= 10)]
range
# Expected Output:
# (array([6, 9, 10]),)

array([ 6,  9, 10])

<details>
    <summary>Answer Q11</summary>
    <hr>
    <pre>

\# Method 1
index = np.where((a >= 5) & (a <= 10))
a[index]

\# Method 2:
index = np.where(np.logical_and(a>=5, a<=10))
a[index]
#> (array([6, 9, 10]),)

\# Method 3: (thanks loganzk!)
a[(a >= 5) & (a <= 10)]
    </pre>
</details>

### 12. How to swap two columns in a 2d numpy array?

Difficulty Level: L2

Q. Swap columns 1 and 2 in the array arr.

In [55]:
# Input
arr = np.arange(9).reshape(3,3)

# Type your code, here
swapped_arr = arr[:,[1,0,2]]
swapped_arr
# Expected result
#> array([[1, 0, 2],
#>        [4, 3, 5],
#>        [7, 6, 8]])

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

<details>
    <summary>Answer Q12</summary>
    <hr>
    <pre>
arr[:,[1,0,2]]
    </pre>
</details>

### 13. How to swap two rows in a 2d numpy array?

Difficulty Level: L2

Q. Swap rows 1 and 2 in the array arr:

In [56]:
# Input
arr = np.arange(9).reshape(3,3)

# Type your code, here
swapped_arr = arr[[1,0,2], :]
swapped_arr

# Expected result
#> array([[3, 4, 5],
#>        [0, 1, 2],
#>        [6, 7, 8]])

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

<details>
    <summary>Answer Q13</summary>
    <hr>
    <pre>
arr[[1,0,2], :]
    </pre>
</details>

### 14. How to reverse the rows of a 2D array?

Difficulty Level: L2

Q. Reverse the rows of a 2D array `arr`.

In [57]:
# Input
arr = np.arange(9).reshape(3,3)

# Type your code, here
swapped_arr = arr[::-1]
swapped_arr

# Expected result
# array([[6, 7, 8],
#        [3, 4, 5],
#        [0, 1, 2]])

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

<details>
    <summary>Answer Q14</summary>
    <hr>
    <pre>
    # Solution
    arr[::-1]
    </pre>
</details>

### 15. How to reverse the columns of a 2D array?

Difficulty Level: L2

Q. Reverse the columns of a 2D array arr.

In [ ]:
# Input
arr = np.arange(9).reshape(3,3)

# Type your code, here

#> array([[2, 1, 0],
#>        [5, 4, 3],
#>        [8, 7, 6]])

<details>
    <summary>Answer Q15</summary>
    <hr>
    <pre>
# Solution
arr[:, ::-1]
    </pre>
</details>

## Misc. Exercises (Optional)

### 1. How to generate custom sequences in numpy without hardcoding?

Difficulty Level: L2

Q. Create the following pattern without hardcoding. Use only numpy functions and the below input array `a`.

In [ ]:
# Input:
a = np.array([1,2,3])

# Type your code, here

# Expected result
#> array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

<details>
    <summary>Answer Q1</summary>
    <hr>
    <pre>
np.r_[np.repeat(a, 3), np.tile(a, 3)]
    </pre>
</details>

### 2. How to create a 2D array containing random floats between 5 and 10?

Difficulty Level: L2 - Ezoic

Q. Create a 2D array of shape 5x3 to contain random decimal numbers between 5 and 10.

In [59]:
# Type your code, here
rand_arr = np.random.uniform(5,10, size=(5,3))
rand_arr

array([[8.79574187, 9.15128698, 8.01787866],
       [7.24399101, 8.49003284, 6.24238573],
       [7.08657086, 5.41802603, 7.43318505],
       [9.84234543, 9.75648095, 7.6891956 ],
       [7.13554099, 8.0025712 , 6.80408599]])

<details>
    <summary>Answer Q2</summary>
    <hr>
    <pre>

\# Solution Method 1:
rand_arr = np.random.randint(low=5, high=10, size=(5,3)) + np.random.random((5,3))

\# Solution Method 2:
rand_arr = np.random.uniform(5,10, size=(5,3))
print(rand_arr)
#> [[ 8.50061025  9.10531502  6.85867783]
#>  [ 9.76262069  9.87717411  7.13466701]
#>  [ 7.48966403  8.33409158  6.16808631]
#>  [ 7.75010551  9.94535696  5.27373226]
#>  [ 8.0850361   5.56165518  7.31244004]]
    </pre>
</details>

### 3. How to print only 3 decimal places in python 

In [60]:
# make rand_arr only print 3 decimal places
np.set_printoptions(precision=3)
rand_arr

array([[8.796, 9.151, 8.018],
       [7.244, 8.49 , 6.242],
       [7.087, 5.418, 7.433],
       [9.842, 9.756, 7.689],
       [7.136, 8.003, 6.804]])